server:
  address: 0.0.0.0
  port: 8080
  shutdown: graceful
  servlet:
    session.cookie.http-only: true

spring:
  application:
    name: Pharma

  jpa:
    open-in-view: false
    properties:
      hibernate.jdbc.time_zone: UTC
      hibernate.format_sql: false
    hibernate:
      ddl-auto: none
    show-sql: false
    database: postgresql
  messages:
    basename: i18n/messages

  flyway:
    enabled: true
    url: jdbc:postgresql://localhost:5432/pharma
    user: el3orb
    password: Pa$$w0rd!
    schemas: pharma
    locations: classpath:db/migration/postgresql

  config:
    import: optional:secrets.yml
