server:
  address: 0.0.0.0
  port: 8080

spring:
  application:
    name: Pharma
  datasource:
    url: jdbc:postgresql://localhost:5432/pharma
    username: el3orb
    password: Pa$$w0rd!
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyJpaCompliantImpl
    show-sql: false
    database: postgresql
    properties:
      hibernate:
        column_ordering_strategy: legacy
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  mail:
    host: smtp.gmail.com
    port: 587

    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  config:
    import: optional:secrets.yml
