server:
  address: 0.0.0.0
  port: 8080

spring:
  application:
    name: Pharma
  datasource:
    url: jdbc:postgresql://localhost:5432/pharma
    username: el3orb
    password: Pa$$w0rd!
    hikari:
      schema: pharma
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    database: postgresql
    properties:
      hibernate:
        format_sql: true
    open-in-view: false

  flyway:
    enabled: true
    url: jdbc:postgresql://localhost:5432/pharma
    user: el3orb
    password: Pa$$w0rd!
    schemas: pharma
    locations: classpath:db/migration/postgresql

  config:
    import: optional:secrets.yml
